### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by fcharras** [oleksandr-pavlyk/py_sandbox_radix_sort_count#1]
@oleksandr-pavlyk maybe you forgot to add a file before pushing ?

```
FAILED: CMakeFiles/_radix.dir/src/_py.cpp.o 
/dev/shm/u154853/oneapi/compiler/2023.1.0/linux/bin/icpx -D_radix_EXPORTS -I/dev/shm/u154853/oneapi/compiler/2023.1.0/linux/include -I/home/u154853/py_sandbox_radix_sort_count/src -I/run/shm/u154853/mambaforge/lib/python3.10/site-packages/dpctl/include -I/run/shm/u154853/mambaforge/lib/python3.10/site-packages/dpctl/include/../../dpctl/tensor/libtensor/include -isystem /home/u154853/py_sandbox_radix_sort_count/_skbuild/linux-x86_64-3.10/cmake-build/_deps/pybind11-src/include -isystem /run/shm/u154853/mambaforge/include/python3.10 -O3 -DNDEBUG -std=gnu++17 -fPIC -fvisibility=hidden -O3 -fno-approx-func -ipo -fsycl -MD -MT CMakeFiles/_radix.dir/src/_py.cpp.o -MF CMakeFiles/_radix.dir/src/_py.cpp.o.d -o CMakeFiles/_radix.dir/src/_py.cpp.o -c /home/u154853/py_sandbox_radix_sort_count/src/_py.cpp
/home/u154853/py_sandbox_radix_sort_count/src/_py.cpp:9:10: fatal error: 'utils/type_dispatch.hpp' file not found
#include "utils/type_dispatch.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/run/shm/u154853/mambaforge/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/run/shm/u154853/mambaforge/lib/python3.10/site-packages/skbuild/cmaker.py", line 696, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/run/shm/u154853/mambaforge/lib/python3.10/site-packages/skbuild/cmaker.py", line 741, in make_impl
    raise SKBuildError(msg)
```

**Comment by oleksandr-pavlyk** [comment]
No,but the repo is incomplete, as cryptically stated in README:

> Requires `dpctl` built in-place.

To build the project, one now needs to do 

```
git clone http://github.com/IntelPython/dpctl.git
git clone http://github.com/oleksandr-pavlyk/py_sandbox_radix_sort.git
pushd dpctl && python scripts/build_locally.py && popd
cd py_sandbox_radix_sort
CC=icx CXX=icpx python setup.py develop -G Ninja -- -DDPCTL_MODULE_PATH=$(python -m dpctl --cmakedir)
```

The reason `dpctl` is needed is that it does not yet package headers from "libtensor/include" in the installed product. This will soon change and this extension can become self-contained.

**Comment by fcharras** [comment]
Oh thank you to point that out, indeed I went too fast and skipped the "build in place" step :facepalm:
